# remember history
HISTSIZE=10000
HISTFILE=~/.zsh_history
SAVEHIST=10000
setopt histverify

# report all login / logouts
# check them every 10 seconds
export WATCH=all
export LOGCHECK=10

# check local mails every minute
export MAILCHECK=60

export PYMACS_PYTHON=python3

# default editor / browser settings
export SVN_EDITOR="{{ mg_binary }}"
export EDITOR="{{ mg_binary }}"
export BROWSER="{{ firefox_binary }}"

{% raw %}

# shell nach x sekunden automatisch schliessen
export TMOUT=0

# Symbolische Links verfolgen
set -P

# terminal blinken und piepen ausstellen
setopt nobeep

# Emacs editing mode
bindkey -e

# change dir without cd
setopt autocd

# more powerful pattern matching features
setopt extended_glob

# use autocorrection of commands
setopt correct

# use autocorrection of parameter
setopt correct_all

# dont cache command locations
setopt hash_cmds

# cache dirs
setopt hash_dirs

# automatically add dirs to directory stack in reverse order
setopt autopushd pushd_minus

# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' completions 1
zstyle ':completion:*' glob 1
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' ''
zstyle ':completion:*' max-errors 1 not-numeric
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' substitute 1

autoload -U compinit
compinit

bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[3~" delete-char

#autoload -U promptinit
#promptinit

#prompt elite2

#export PS1="--:[%* | %n@%m:%c$ "
#export RPROMPT="[%D{%d.%m}]"
export PS1="
--:[ Jobs: %j | Hist: %h | Term: %y | Date: %D{%d.%m.%Y}
[%*] %n@%m:%c$ "

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias tripwire='LC_ALL=C /usr/sbin/tripwire'

alias em="emacs -nw"
alias b="popd"
alias g="xscreensaver-command -lock &"
alias l='ls -aluih'
alias m='tail -f /var/log/messages'
alias n='netstat -anp | grep LISTEN'
alias p='ps -e -o ppid,pid,%cpu,%mem,stackp,tty,user,state,cmd'
alias psg="ps ax | grep"
alias psm="ps -e -o size,rss,pid,cmd|sort -h"
alias okm="setxkbmap de"
alias nkm="setxkbmap de -variant dvorak"

alias praesi_on="sudo xrandr --output LVDS1 --mode 800x600 --output VGA1 --mode 800x600 --same-as LVDS1"
alias praesi_off="sudo xrandr --output VGA1 --off; sudo xrandr --output LVDS1 --mode 1024x600"

alias play_on="xrandr --size 800x600"
alias play_off="xrandr --size 1024x600"

{% endraw %}