---
- name: copy element gpg key
  copy:
    src: element-io-archive-keyring.gpg
    dest: /usr/share/keyrings/element-io-archive-keyring.gpg
    owner: rppt 
    group: root 
    mode: 0644
  when: ansible_os_family == "Debian"

- name: copy element deb repo 
  copy:
    src: element.repo
    dest: /etc/apt/sources.list.d/element-io.list
    owner: root 
    group: root
    mode: 0644
  register: element_repo
  when: ansible_os_family == "Debian"

- name: apt update
  command: apt update
  when: element_repo.changed

- name: Install Matrix chat client
  snap:
    name: element-desktop
    state: present
