---
- include_vars: '{{ ansible_os_family }}.yml'
  
- name: install mail user agent
  package:
    name: '{{ my_mua }}'
    state: present

- name: install mail user agent addons
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ my_mua_addons }}'

- name: install spam filter
  package:
    name: '{{ my_spam_filter }}'
    state: present
