---
- include_vars: '{{ ansible_os_family }}.yml'
  
- name: install mplayer
  package:
    name: 'mplayer'
    state: present

- name: install gstreamer plugins
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ gstreamer1_plugins_good }}"
    - "{{ gstreamer1_plugins_bad }}"
    - "{{ gstreamer1_plugins_ugly }}"
