#!/bin/sh

# startup /home/.fluxbox/startup
# exec fluxbox
# exec startxfce4
# exec wmaker
#  exec e16
#exec enlightenment_start

xmodmap -e "keycode 96 = Super_L"
export LC_ALL="en_US.UTF-8"

exec openbox-session
