---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install xbindkeys
  package:
    name: 'xbindkeys'
    state: latest

- name: install xscreensaver
  package:
    name: 'xscreensaver'
    state: latest

- name: x startup config
  copy:
    src: xinitrc
    dest: '{{ desktop_xstartup_script }}'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0700

- name: xbindkeys config
  template:
    src: xbindkeysrc.j2
    dest: '{{ my_home }}/.xbindkeysrc'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0440
