---
- include_vars: '{{ ansible_os_family }}.yml'

- name: create xorg.conf.d dir
  file:
    path: '/etc/X11/xorg.conf.d'
    state: directory
    recurse: yes
    owner: 'root'
    group: 'root'

- name: xorg keyboard config
  copy:
    src: xorg_keyboard.conf
    dest: '/etc/X11/xorg.conf.d/xorg_keyboard.conf'
    owner: 'root'
    group: 'root'
    mode: 0744

- name: xorg synaptics config
  copy:
    src: xorg_synaptics.conf
    dest: '/etc/X11/xorg.conf.d/xorg_synaptics.conf'
    owner: 'root'
    group: 'root'
    mode: 0744

- name: install xbindkeys
  package:
    name: 'xbindkeys'
    state: present

- name: install xscreensaver
  package:
    name: 'xscreensaver'
    state: present

- name: x startup config
  copy:
    src: xinitrc
    dest: '{{ desktop_xstartup_script }}'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0700

- name: xbindkeys config
  template:
    src: xbindkeysrc.j2
    dest: '{{ my_home }}/.xbindkeysrc'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0440
