---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install tcpdump
  package:
    name: 'tcpdump'
    state: present
  when: ansible_os_family != 'OpenBSD'
    
- name: install jnettop
  package:
    name: 'jnettop'
    state: present
