---
- name: install dhcp server 
  package:
    name: isc-dhcp-server
    state: present 

- name: configure dhcp as pxe server 
  copy:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: 'root'
    group: 'root'
    mode: 0644

- name: Config dhcpd debian defaults
  template:
    src: debian-isc-dhcp-server-default
    dest: /etc/default/isc-dhcp-server
    owner: root 
    group: root 
    mode: 0644 
  when: ansible_os_family == "Debian"

- name: install tftp server 
  package:
    name: tftpd-hpa
    state: present 

- name: Install Debian Stable x64 pxe image 
  get_url:
    url: http://ftp.ch.debian.org/debian/dists/stable/main/installer-amd64/current/images/netboot/netboot.tar.gz
    dest: /tmp/debian-netboot64.tgz

- name: Unpack Debian Stable x64 pxe image 
  archvive:
    src: /tmp/debian-netboot64.tgz
    dest: /srv/tftp

- name: Link boot image 
  file:
    state: link 
    src: /srv/tftp/debian-installer/amd64/bootnetx64.efi
    dest: /srv/tftp/bootnetx64.efi

- name: Get OpenBSD pxe image 
  get_url:
    url: "https://ftp.ch.openbsd.org/pub/OpenBSD/7.1/i386/{{ item }}"
    dest: "/srv/tftp/{{ item }}"
  with_items:
    - pxeboot
    - bsd.rd

- name: Create tftpd etc directory
  file:
    state: directory
    path: /src/tftp/etc
    owner: root 
    group: root 
    mode: 0755 

- name: Copy boot.conf 
  copy:
    src: boot.conf
    dest: /src/tftp/etc/boot.conf
    owner: root 
    group: root 
    mode: 0644

