---

- name: install aide
  package:
    name: 'aide'
    state: present

- name: configure aide
  copy:
    src: "{{ aide_config }}"
    dest: '{{ aide_config_dest }}'
    owner: 'root'
    group: 'root'
    mode: 0600
  register: aide_config

- name: init aide db
  command: aide --init --config {{ aide_config_dest }}
  when: aide_config.changed
