---

- name: Copy kernel security grub conf
  copy:
    src: grub.conf
    dest: /etc/grub.d/01_security.cfg
    owner: root 
    group: root 
    mode: 0644
  when: ansible_os_family == "Debian"
  register: kernel_config

- name: Update grub config
  command: update-grub
  when: kernel_config.changed
