---
- include_vars: '{{ ansible_os_family }}.yml'
  
- name: install gnupg
  package:
    name: 'gnupg'
    state: present

- name: install aide
  package:
    name: 'aide'
    state: present

- name: configure aide
  copy:
    src: "{{ aide_config }}"
    dest: '{{ aide_config_dest }}'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0600

- name: configure sysctl 
  copy:
    src: '{{ sysctl_config }}'
    dest: '{{ sysctl_config_dest }}'
    owner: 'root'
    group: 'root'
    mode: 0600

- name: configure packetfilter
  copy:
    src: '{{ packetfilter_config }}'
    dest: '{{ packetfilter_config_dest }}'
    owner: 'root'
    group: 'root'
    mode: 0600
  when: ansible_os_family != 'Darwin'
