---

- name: install iptables-persistent
  package:
    name: iptables-persistent
    state: present
  when: ansible_os_family == 'Debian'

- name: configure packetfilter
  copy:
    src: '{{ packetfilter_config }}'
    dest: '{{ packetfilter_config_dest }}'
    owner: 'root'
    group: 'root'
    mode: 0600
  when: ansible_os_family != 'Darwin'

- name: configure ipv6 packetfilter
  copy:
    src: '{{ packetfilter_config }}'
    dest: '/etc/iptables/rules.v6'
    owner: 'root'
    group: 'root'
    mode: 0600
  when: ansible_os_family == 'Debian'

- name: replace icmp with icmpv6 in ipv6 packetfilter config 
  lineinfile:
    path: '/etc/iptables/rules.v6'
    backrefs: true
    regexp: '^(.+) icmp (.+)$'
    line: '\1 icmpv6 \2'

- name: Start iptables service
  service:
    name: iptables
    enabled: yes
    state: started
  when: ansible_os_family == 'Debian'
