firefox_binary: "/usr/bin/firefox"
my_mua_addons: "claws-mail-plugins-bogofilter"
gstreamer1-plugins-good: "gstreamer1-plugins-good-free"
gstreamer1-plugins-bad: "gstreamer1-plugins-bad"
gstreamer1-plugins-ugly: "gstreamer1-plugins-ugly"


