---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install latex
  package:
    name: '{{ texlive_package }}'
    state: present

- name: install pdf reader
  package:
    name: '{{ my_pdf_reader }}'
    state: present

- name: install dictionary
  package:
    name: 'mozilla-dicts-{{ my_dict_lang }}'
    state: present

- name: link dict
  file:
    follow: yes
    src: '/usr/local/share/mozilla-dicts/{{ my_dict_lang }}.aff'
    dest: '/usr/local/share/hunspell/{{ my_dict_lang }}.aff'
    state: link
  file:
    follow: yes
    src: '/usr/local/share/mozilla-dicts/{{ my_dict_lang }}.dic'
    dest: '/usr/local/share/hunspell/{{ my_dict_lang }}.dic'
    state: link
  when: ansible_os_family == "OpenBSD"

