---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install libreoffice
  package:
    name: 'libreoffice'
    state: latest

- name: install latex
  package:
    name: '{{ texlive_package }}'
    state: latest

- name: install owncloud client
  package:
    name: '{{ owncloud_client_package }}'
    state: latest

- name: install pdf reader
  package:
    name: '{{ my_pdf_reader }}'
    state: latest
