---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install wireshark
  package:
    name: '{{ wireshark_package }}'
    state: present

- name: Add user to wireshark group
  user:
    name: "{{ my_user }}"
    groups:
      - wireshark
    append: yes

- name: copy wireshark preferences
  copy:
    src: preferences.conf
    dest: "{{ my_home }}/.config/wireshark/preferences"
    owner: "{{ my_user }}"
    group: "{{ my_user }}"

- name: create wireshark profile dirs
  file:
    path: "{{ my_home }}/.config/wireshark/profiles/{{ item }}/"
    state: directory
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
  with_items: "{{ wireshark_profiles }}"

- name: copy wireshark profiles
  copy:
    src: "{{ item }}-profile"
    dest: "{{ my_home }}/.config/wireshark/profiles/{{ item }}/preferences"
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
  with_items: "{{ wireshark_profiles }}"

- name: copy wireshark dfilter buttons
  copy:
    src: dfilter_buttons
    dest: "{{ my_home }}/.config/wireshark/profiles/{{ item }}/dfilter_buttons"
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
  with_items: "{{ wireshark_profiles }}"

- name: copy wireshark dfilter macros
  copy:
    src: dfilter_macros
    dest: "{{ my_home }}/.config/wireshark/profiles/{{ item }}/dfilter_macros"
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
  with_items: "{{ wireshark_profiles }}"
