---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install zsh
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - zsh
    - '{{ autojump_package }}'

- name: configure zsh
  copy:
    src: zshrc
    dest: '{{ my_home }}/.zshrc'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0600
