---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install zsh
  package:
    name: zsh
    state: latest

- name: install autojump
  package:
    name: '{{ autojump_package }}'
    state: latest

- name: configure zsh
  copy:
    src: zshrc
    dest: '{{ my_home }}/.zshrc'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0600
