---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install zsh
  package:
    name: zsh
    state: present

- name: install zsh autojump
  package:
    name: '{{ autojump_package }}'
  when: ansible_os_family != "OpenBSD"
  
- name: configure zsh
  template:
    src: zshrc
    dest: '{{ my_home }}/.zshrc'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0600
