---
- name: enable apmd
  lineinfile:
    path: /etc/rc.conf.local
    line: 'apmd_flags='
    insertbefore: EOF
  when: ansible_os_family == "OpenBSD"

- name: install anacron
  package: 
    name: anacron 
    state: present
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: start anacron service 
  service:
    name: anacron
    enabled: yes
    state: started
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: install tlp
  package: 
    name: tlp
    state: present
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: copy tlp config
  copy:
    src: tlp.conf
    dest: /etc/tlp.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
  
- name: Start tlp service
  service:
    name: tlp
    enabled: yes
    state: started
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
