---
- name: Install GOG Galaxy
  snap: 
    name: gog-galaxy-wine
    state: present 

- name: Create DPKG architecture
  file: 
    path: /var/lib/dpkg/arch
    state: touch
  register: dpkg_architecture

- name: Check DPKG architecture
  lineinfile: 
    name: /var/lib/dpkg/arch
    line: i386
    state: present

- name: Activate i386 packages for APT
  command: dpkg --add-architecture i386
  register: dpkg
  when: ansible_os_family == "Debian" and dpkg_architecture.changed

- name: APT Update
  command: apt update
  when: dpkg.changed

- name: Enable the RPM Fusion repository
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_os_family == 'RedHat'

- name: install Steam 
  package:
    name: steam 
    state: present 
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
