---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install emacs
  package:
    name: '{{ emacs_package }}'
    state: present

- name: install mg
  package:
    name: 'mg'
    state: present
  when: ansible_os_family != "OpenBSD"

- name: configure mg
  copy:
    src: mg.conf
    dest: '{{ my_home }}/.mg'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0600

- name: install xclip
  package:
    name: 'xclip'
    state: present

- name: install emacs auctex
  package:
    name: '{{ auctex_package }}'
    state: present
  when: ansible_os_family != "OpenBSD" and ansible_os_family != "Archlinux"

- name: install gxmessage
  package:
    name: gxmessage 
    state: present
  when: ansible_os_family != "OpenBSD"


- name: clone emacs config
  become_user: '{{ my_user }}'
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/emacs'
    repo: https://github.com/balle/emacs.git
  when: ansible_os_family != "OpenBSD"

- name: clone emacs config
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/emacs'
    repo: https://github.com/balle/emacs.git
  when: ansible_os_family == "OpenBSD"

- name: link .emacs
  file:
    follow: yes
    src: '{{ my_home }}/emacs/.emacs'
    dest: '{{ my_home }}/.emacs'
    state: link

- name: link .emacs.d
  file:
    follow: yes
    src: '{{ my_home }}/emacs/.emacs.d'
    dest: '{{ my_home }}/.emacs.d'
    state: link


