---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install emacs
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ emacs_package }}'
    - emacs-auctex
    - gxmessage
    - xclip
    
- name: clone emacs config
  become_user: '{{ my_user }}'
  git:
    clone: yes
    dest: '{{ my_home }}/emacs'
    repo: https://github.com/balle/emacs.git

- name: link .emacs
  file:
    follow: yes
    src: '{{ my_home }}/emacs/.emacs'
    dest: '{{ my_home }}/.emacs'
    state: link

- name: link .emacs.d
  file:
    follow: yes
    src: '{{ my_home }}/emacs/.emacs.d'
    dest: '{{ my_home }}/.emacs.d'
    state: link

- name: link .emacs-snippets
  file:
    follow: yes
    src: '{{ my_home }}/emacs/.emacs-snippets'
    dest: '{{ my_home }}/.emacs-snippets'
    state: link

