---

- name: install golang
  package:
    name: '{{ go_package }}'
    state: present

- name: install go modules
  command: "{{ item }}"
  become_user: "{{ my_user }}"
  become_method: "su"
  loop:
    - go get -u -v golang.org/x/tools/cmd/guru
    - go get -u -v github.com/rogpeppe/godef
    - go get -u -v github.com/nsf/gocode
    - go get -u -v golang.org/x/tools/cmd/goimports
    - go get -u -v github.com/dougm/goflymake
    - go get -u github.com/motemen/gore/cmd/gore
