---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install gcc
  package:
    name: gcc
    state: latest
  when: ansible_os_family != 'OpenBSD'

- name: install make
  package:
    name: make
    state: latest
  when: ansible_os_family != 'OpenBSD'

- name: install automake
  package:
    name: automake
    state: latest
  when: ansible_os_family != 'OpenBSD'

- name: install autoconf
  package:
    name: autoconf
    state: latest
  when: ansible_os_family != 'OpenBSD'

- name: install patch
  package:
    name: patch
    state: latest
  when: ansible_os_family != 'OpenBSD'

- name: install python3
  package:
    name: '{{ python3_package }}'
    state: latest

- name: install python 3 pip 
  package:
    name: '{{ python3_pip_package }}'
    state: latest

- name: install python 3 virtualenv 
  package:
    name: '{{ python3_virtualenv_package }}'
    state: latest

- name: link python3
  file:
    follow: yes
    src: '/usr/local/bin/python3.6'
    dest: '/usr/bin/python3'
    state: link
  when: ansible_os_family == 'OpenBSD'

- name: link pydoc3
  file:
    follow: yes
    src: '/usr/local/bin/pydoc3.6'
    dest: '/usr/local/bin/pydoc3'
    state: link
  when: ansible_os_family == 'OpenBSD'

- name: install common lisp
  package:
    name: '{{ sbcl_package }}'
    state: latest

- name: clone lisp snippets
  git:
    clone: yes
    dest: '{{ my_home }}/lisp'
    repo: https://github.com/balle/lisp-snippets.git

- name: install erlang
  package:
    name: '{{ erlang_package }}'
    state: latest

- name: clone erlang snippets
  git:
    clone: yes
    dest: '{{ my_home }}/erlang'
    repo: https://github.com/balle/erlang-snippets.git
