---
- name: install libperl-dev
  package:
    name: libperl-dev 
    state: present 
  when: ansible_os_family == 'Debian'

- name: install perl-devel
  package:
    name: perl-devel 
    state: present 
  when: ansible_os_family == 'RedHat'

- name: install cpanminus
  package:
    name: cpanminus
    state: present 
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Archlinux'

- name: install perl-App-cpanminus
  package:
    name: perl-App-cpanminus
    state: present 
  when: ansible_os_family == 'RedHat'

- name: install perlbrew
  package:
    name: perlbrew 
    state: present 
  
- name: install Perl::LanguageServer
  command: cpanm Perl::LanguageServer

- name: install Devel::Cover
  package:
    name: libdevel-cover-perl
    state: present 
  when: ansible_os_family == 'Debian'
