---

- name: install python3
  package:
    name: '{{ python3_package }}'
    state: present

- name: install python 3 pip
  package:
    name: '{{ python3_pip_package }}'
    state: present

- name: install python 3 virtualenv
  package:
    name: '{{ python3_virtualenv_package }}'
    state: present

- name: link python3
  file:
    follow: yes
    src: '/usr/local/bin/python3.8'
    dest: '/usr/bin/python3'
    state: link
  when: ansible_os_family == 'OpenBSD'

- name: link pydoc3
  file:
    follow: yes
    src: '/usr/local/bin/pydoc3.8'
    dest: '/usr/local/bin/pydoc3'
    state: link
  when: ansible_os_family == 'OpenBSD'

- name: install ipython3
  package:
    name: '{{ ipython3_package }}'
    state: present

- name: install pudb
  package:
    name: '{{ pudb_package }}'
    state: present
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' or ansible_os_family == 'OpenBSD'

- name: pip install pudb 
  command: pip3 install pudb 
  when: ansible_os_family != 'Debian' and ansible_os_family != 'RedHat' and ansible_os_family != 'OpenBSD'

- name: install poetry
  command: pip3 install poetry
  when: ansible_os_family != 'Debian'

- name: install poetry
  package:
    name: python3-poetry
    state: present
  when: ansible_os_family == 'Debian'
