---
- name: install tmux
  package:
    name: tmux
    state: latest
  when: ansible_os_family != "OpenBSD"

- name: configure tmux
  copy:
    src: tmux.conf
    dest: '{{ my_home }}/.tmux.conf'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0440

