---
- name: install tmux
  package:
    name: tmux
    state: latest

- name: configure tmux
  copy:
    src: tmux.conf
    dest: '{{ my_home }}/.tmux.conf'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0440

- name: make tmux.d dir
  file:
    path: '{{ my_home }}/.tmux.d'
    state: directory

- name: make tmux.d plugins dir
  file:
    path: '{{ my_home }}/.tmux.d/plugins'
    state: directory

- name: copy tmux startup script
  copy:
    src: startup.sh
    dest: '{{ my_home }}/.tmux.d/startup.sh'
    owner: '{{ my_user }}'
    group: '{{ my_group }}'
    mode: 0700

- name: git clone tpm
  git:
    clone: yes
    dest: '{{ my_home }}/.tmux.d/tpm'
    repo: https://github.com/tmux-plugins/tpm.git
