---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install libvirt
  package:
    name: "{{ libvirt_package }}"
    state: present
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: install virt-viewer
  package:
    name: "{{ virt_viewer_package }}"
    state: present
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: install guestfs-tools
  package:
    name: "{{ guestfs_tools_package }}"
    state: present
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
