---
- name: install sleuthkit
  package:
    name: 'sleuthkit'
    state: present

- name: install autopsy
  package:
    name: 'autopsy'
    state: present
  when: ansible_os_family != "OpenBSD"
  
- name: install testdisk
  package:
    name: 'testdisk'
    state: present

- name: install foremost
  package:
    name: 'foremost'
    state: present

- name: install volatility framework
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/volatility'
    repo: https://github.com/volatilityfoundation/volatility

