---
- name: install john
  package:
    name: john
    state: present

- name: install hydra
  package:
    name: hydra
    state: present

- name: install medusa
  package:
    name: medusa
    state: present

- name: install hashcat
  package: 
    name: hashcat
    state: present
    
- name: install fcrackzip
  package: 
    name: fcrackzip
    state: present
    
- name: install pdfcrack
  package:
    name: pdfcrack
    state: present
    
- name: clone SecLists
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/SecLists'
    repo: 'https://github.com/danielmiessler/SecLists'

- name: clone Kali wordlists
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/KaliWordlists'
    repo: https://gitlab.com/kalilinux/packages/wordlists.git
  
- name: install cewl 
  package:
    name: cewl
    state: present

- name: Download default password list 
  get_url:
    url: https://raw.githubusercontent.com/many-passwords/many-passwords/main/passwords.csv
    dest: '{{ my_home }}/hack/DefaultPasswords.csv'
