---
- name: install dsniff
  package:
    name: '{{ dsniff_package }}'
    state: present
  when: ansible_os_family != 'Darwin'
  
- name: install ettercap
  package:
    name: '{{ ettercap_package }}'
    state: present

