---
- include_vars: '{{ ansible_os_family }}.yml'
- include: metasploit.yml
- include: wifi.yml
- include: hijacking.yml
- include: web.yml
- include: bluetooth.yml

- name: install nmap
  package:
    name: 'nmap'
    state: present

- name: clone routersploit
  git:
    clone: yes
    dest: '{{ my_home }}/routersploit'
    repo: 'https://github.com/threat9/routersploit.git'

- name: install routersploit dependencies
  command: chdir="{{ my_home }}/routersploit" "python3 -m pip install -r requirements.txt"
  run_once: True
  
