---
- include_vars: '{{ ansible_os_family }}.yml'

- name: install nmap
  package:
    name: 'nmap'
    state: present

- name: install aircrack-ng
  package:
    name: 'aircrack-ng'
    state: present

- name: install dsniff
  package:
    name: '{{ dsniff_package }}'
    state: present
  when: ansible_os_family != 'Darwin'
  
- name: install ettercap
  package:
    name: '{{ ettercap_package }}'
    state: present

- name: install zed attack proxy
  package:
    name: '{{ zap_package }}'
    state: present
  when: ansible_os_family != 'FreeBSD'

- name: clone metasploit
  git:
    clone: yes
    dest: '{{ my_home }}/metasploit'
    repo: 'https://github.com/rapid7/metasploit-framework.git'

- name: install ruby
  package: 
    name: "{{ ruby_package }}"
    state: present
- name: link bundler
  file:
    follow: yes
    src: '/usr/local/bin/bundle27'
    dest: '/usr/local/bin/bundle'
    state: link
  when: ansible_os_family == 'OpenBSD'

- name: install metasploit dependencies
  command: chdir="{{ my_home }}/metasploit" "bundle install"
  run_once: True

- name: clone w3af
  git:
    clone: yes
    dest: '{{ my_home }}/w3af'
    repo: 'https://github.com/andresriancho/w3af.git'

