---
- include_vars: '{{ ansible_os_family }}.yml'

- name: Create hack dir 
  file: 
    path: "{{ my_home }}/hack"
    state: directory
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    mode: 0700

- include: metasploit.yml
- include: wifi.yml
- include: network.yml
- include: bluetooth.yml
- include: cracking.yml
- include: web.yml
- include: reveng.yml
- include: misc.yml
