---
- name: clone evilgrade
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/evilgrade'
    repo: 'https://github.com/infobyte/evilgrade'
    
- name: install recon-ng
  package:
    name: recon-ng
    state: present
    