---
- name: clone evilgrade
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/evilgrade'
    repo: 'https://github.com/infobyte/evilgrade'
    
- name: install recon-ng
  package:
    name: recon-ng
    state: present

- name: Download mac oui db 
  get_url:
    url: https://maclookup.app/downloads/csv-database/get-db?t=22-12-10&h=150820948dce1e74f1fabeaea44afa717fd10b37
    dest: '{{ my_home }}/hack/macoui.csv'

- name: install gitlab scanner truffle hog 
  git:
    clone: yes 
    forcce: yes 
    repo: 'https://github.com/trufflesecurity/trufflehog.git'
    dest: '{{ my_home }}/hack/trufflehog'

- name: install metagoofil
  git:
    clone: yes 
    forcce: yes 
    repo: 'https://github.com/opsdisk/metagoofil.git'
    dest: '{{ my_home }}/hack/metagoofil'

- name: install metagoofil dependencies
  command: python3 -m pip install -r requirements.txt
  args:
    chdir: "{{ my_home }}/hack/metagoofil"
  run_once: True

- name: install exiftool
  package:
    name: exiftool
    state: present
