---
- name: install nmap
  package:
    name: 'nmap'
    state: present

- name: clone routersploit
  git:
    clone: yes
    dest: '{{ my_home }}/hack/routersploit'
    repo: 'https://github.com/threat9/routersploit.git'

- name: install routersploit dependencies
  command: python3 -m pip install -r requirements.txt
  args:
    chdir: "{{ my_home }}/routersploit"
  run_once: True

- name: install dsniff
  package:
    name: '{{ dsniff_package }}'
    state: present
  when: ansible_os_family != 'Darwin'
  
- name: install ettercap
  package:
    name: '{{ ettercap_package }}'
    state: present

