---
- name: install zed attack proxy on macOS
  package:
    name: '{{ zap_package }}'
    state: present
  ignore_errors: yes
  when: ansible_os_family == 'Darwin'

- name: install zed attack proxy on OpenBSD
  package:
    name: '{{ zap_package }}'
    state: present
  when:
    - ansible_os_family == 'OpenBSD'

- name: install zed attack proxy on Linux
  snap:
    name: '{{ zap_package }}'
    state: present
    classic: yes
  when:
    - ansible_os_family == 'Debian' or ansible_os_family == "RedHat"

- name: install sqlmap
  package:
    name: sqlmap 
    state: present 

- name: clone nosqlmap
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/nosqlmap'
    repo: 'https://github.com/SirKnightV/NoSQLMap-Python3-update.git'
  register: nosqlmap

- name: install nosqlmap requirements 
  command: pip3 install -r requirements.txt
  args:
    chdir: '{{ my_home }}/hack/nosqlmap'
  when: nosqlmap.changed

- name: install pymongo
  package:
    name: python3-pymongo
    state: present

- name: install whatweb
  package:
    name: whatweb
    state: present
    
- name: install nikto
  package:
    name: whatweb
    state: present
