---
- name: install aircrack-ng
  package:
    name: 'aircrack-ng'
    state: present

- name: install wifite
  package:
    name: wifite
    state: present

- name: install reaver
  package:
    name: reaver
    state: present

- name: Install bettercap dependencies 
  package: 
    name: "{{ item }}"
    state: present 
  with_items: 
    - golang
    - git
    - build-essential 
    - libpcap-dev 
    - libusb-1.0-0-dev 
    - libnetfilter-queue-dev

- name: Get bettercap
  shell: go get github.com/bettercap/bettercap
  args:
    creates: "$GOPATH/src/github.com/bettercap/bettercap"
  register: bettercap 

- name: Install bettercap 
  shell: make build install
  args:
    chdir: "$GOPATH/src/github.com/bettercap/bettercap" 
  when: bettercap.changed

- name: clone airpwn-ng
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/airpwn-ng'
    repo: 'https://github.com/ICSec/airpwn-ng'

- name: install wifiphishers dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - libnl-3-dev 
    - libnl-genl-3-dev

- name: clone wifiphisher
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/wifiphisher'
    repo: 'https://github.com/wifiphisher/wifiphisher'

- name: install pmkid tools
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - hcxdumptool
    - hcxtools

- name: install alfa awus1900 driver dependencies 
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - make
    - gcc 
    - dkms
  
- name: clone rtl8814au driver src
  git:
    clone: yes
    force: yes
    dest: '/usr/src/rtl8814au-4.3.21'
    repo: 'https://github.com/zebulon2/rtl8814au.git'
  register: rtl8814au

- name: build rtl8814au driver 
  shell: dkms build -m rtl8814au -v 4.3.21 && dkms install -m rtl8814au -v 4.3.21
  when: rtl8814au.changed
