---
- name: install aircrack-ng
  package:
    name: 'aircrack-ng'
    state: present

- name: install wifite
  package:
    name: wifite
    state: present

- name: clone pyrit
  git:
    clone: yes
    dest: '{{ my_home }}/hack/pyrit'
    repo: 'https://github.com/JPaulMora/Pyrit'
