---
- name: install aircrack-ng
  package:
    name: 'aircrack-ng'
    state: present

- name: install wifite
  package:
    name: wifite
    state: present

- name: install reaver
  package:
    name: reaver
    state: present

- name: clone pyrit
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/pyrit'
    repo: 'https://github.com/JPaulMora/Pyrit'

- name: clone airpwn-ng
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/airpwn-ng'
    repo: 'https://github.com/ICSec/airpwn-ng'

- name: clone wifiphisher
  git:
    clone: yes
    force: yes
    dest: '{{ my_home }}/hack/wifiphisher'
    repo: 'https://github.com/wifiphisher/wifiphisher'

- name: install hcxdumptool
  package:
    name: hcxdumptool
    state: present
